name: 2022-focused-cani-comparisons
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - pandas>=1.5.1
  - seaborn>=0.12.0
  - sourmash>=4.5.0,<5
  - tqdm
  - jupyterlab
  - snakemake=7.18.1
